os: osx
language: node_js
node_js: 8
sudo: false

matrix:
  allow_failures:
    - os: osx
  fast_finish: true

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi

cache:
  yarn: true

install:
  - curl -L https://yarnpkg.com/latest.tar.gz | tar xz && mv yarn-* $HOME/.yarn
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn

script:
  - yarn build
